Adding the ab tests to the registration form
Syncano/syncano.com pull request #505
Opened 2017-06-27 09:13 UTC by mgebala8

2017-06-27 10:17 UTC, Idered commented
Resolve conflicts and check comments here: https://github.com/Syncano/syncano.com/pull/503

2017-06-27 13:40 UTC, mgebala8 commented
ok done

2017-06-27 14:17 UTC, Idered requested changes

2017-06-27 14:17 UTC, Idered commented on src/components/shared/auth/signup.js
> +const SignUpForm = ({email, password, toggleModal, register, messages,social}) => (
Space after comma

2017-06-27 14:17 UTC, Idered commented on src/components/ui/page/index.js
>      <Modal
No need to put name attribute on a new line, it will fit perfectly in one line.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        display: block;
By using `div` instead of `span` you can ommit this property.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        display: block;
Also give that span a proper class. Styling classless tags is not flexible.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +      .SignDescription__img {
Can't you give this class to `img` tag and ommit wrapping div?

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        font-family: Roboto;
Roboto is default font. Why did you put it here? Don't just copy paste all css properties from zeplin. 

Also margin, width, height - remove those. This element should fill parent.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        text-align: left;
You can remove `text-align: left;` here and add it to `.SignDescription` class.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        width: auto;
Really needed?

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        font-family: Roboto;
It's default font, you can remove this property.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +        opacity: 0.8;
You can mix together opacity and color: `color: rgba(0,0,0, .8)` just check rgb value of hex color.

2017-06-27 14:17 UTC, Idered commented on src/components/ui/sign-description.js
> +
Remove empty line

2017-06-27 14:17 UTC, Idered commented on src/views/landing/index.js
> +    if (e.target.className.indexOf('version2') > 0){ modalName = 'signupver2' }
```js
const version = e.target.className.split(' ').find(item => /version/.test(item))
const modalName = {
  version1: 'signupver1',
  version2: 'signupver2',
  version3: 'signupver3'
}[version || 'version1']
```

Or even better, if you change `signupver1` (and other names) to `signup-version1` you can do this:

```js
const version= e.target.className.split(' ').find(item => /version/.test(item))
const modalName = `signup-${version || 'version1'}`
```

2017-06-27 15:18 UTC, mgebala8 commented on src/views/landing/index.js
> +    if (e.target.className.indexOf('version2') > 0){ modalName = 'signupver2' }
I understand but sometimes the class has newline characters, maybe a use: 
```
const version = e.target.className.replace(/[\r\n]+/g," ").split(' ').find(item => /version/.test(item))
const modalName = `signup-${version || 'version1'}`
toggleModal(modalName) 
```

2017-06-27 16:23 UTC, Idered commented
@mgebala8 checkout my commits and check if it's working for you. Also please review my commits.

2017-06-28 09:25 UTC, Idered approved these changes

2017-06-28 09:27 UTC, merged